name: trustfund_app
description: A Flutter crowdfunding app using Web3

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  web3dart: ^2.7.3
  http: ^1.1.0

  provider: ^6.1.1

  intl: ^0.18.1
  google_fonts: ^6.1.0
  animate_do: ^3.1.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9

  bip39: ^1.0.6
  ed25519_hd_key: ^2.2.0
  hex: ^0.2.0
  flutter_secure_storage: ^9.0.0

  cupertino_icons: ^1.0.2

  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/contract_abi.json
    - assets/images/